### ISSUE TITLE
Topics to cover in Collaboration

### ISSUE THREAD

**Issue by dcsoto** [computer-aided-biotech/better-cb#11]
Main tools to cover:
- [x] Share notebooks: static (GitHub, NBViewer, Kyso), interactive (Binder, Google Colab), comparative (NBreview) D
- [x] Share code: Git branching, simple GitFlow, code review (good reviewing practices) and good coding practices (linter, style guides) B
- [x] Share pipelines: workflows (Bash scripts, Make, Snakemake, Nextflow) D
- [x] Make tests: test correctness (pytest), test coverage (codecov), implement test pipeline (tox, Travis CI, GitHub actions) B
- [x] Make papers: Tools for collaborative manuscript writing (Manubot, Overleaf, Authorea, GDocs, Office 365) D

**Comment by dcsoto** [comment]
Share pipelines:  
* Bash scripts (set -eo pipefail more info [here](https://gist.github.com/outro56/4a2403ae8fefdeb832a5))

**Comment by dcsoto** [comment]
Consider adding in this section:
- Common workflow language
- Citation Style Language
- Writing manuscript in LaTeX or R Markdown (https://github.com/svmiller/svm-r-markdown-templates)

**Comment by dcsoto** [comment]
Let's add a supplementary figure with an example of a wrong github branching structure and a right one.

**Comment by dcsoto** [comment]
I just realized there is a GitHub command line utility to avoid using the desktop application, maybe we want to include something about it briefly! Here there is more information: https://cli.github.com/

**Comment by BenjaSanchez** [comment]
@dcsoto great! will add it to the code section ;)
