### ISSUE TITLE
Case studies to include

### ISSUE THREAD

**Issue by BenjaSanchez** [computer-aided-biotech/better-cb#14]
I think 2-3 case studies would probably be optimal, each with examples at all 3 scales. For instance:

* Analysis of NGS data (e.g. transcriptomics): From a small case with 2/3 conditions to a full pipeline development.
* Tool development: From a collection of scripts for a one-time routine to a proper command line tool.
* Genome-scale modeling: From using a model for a specific application to generating/maintaining a community model.

@dcsoto what do you think?

**Comment by dcsoto** [comment]
Yes, I think we should include all those 3 examples! Each one highlights one aspect of computational biology. Of course, it's not a comprehensive list, but it will give readers a good set of "templates" that they can adapt for their own projects.

Find below some thoughts related to each one of these. My level of expertise is ranked as ★☆☆☆ (I know what you are talking about, but I have 0 experience on this), ★★☆☆ (I did it a long time ago, I need a huge refresh), ★★★☆ (I have experience on some aspect of this, in others I need a refresh), and ★★★★ (I got this!).

- **Analysis of NGS:** It can go on several ways, but I think this section should focus on the biological question. Importantly, NGS analysis is becoming a "big data" field given the huge amount of information generated everyday. So it would make sense to have a "big data" example. Regardless, here are some examples for this section:
  - Differential expression analysis: straight-forward, 2 or more conditions, looking at genes differentially expressed between each one, getting some nice take-home message. (Dani: ★★★★, Ben: ★★★☆)
  - Population genetics analysis: call small variant in individuals and calculate ancestry and/or signatures of selection (Dani: ★★★☆, Ben: ★☆☆☆)
  - Genome-wide association studies: they look for correlations between genetic variants and phenotypes. Very standard analysis in genomics. I need to do some GWAS in the future, but I haven't gotten there yet. (Dani: ★★☆☆, Ben: ★☆☆☆)
- **Tool development:** I think we should highlight a tool in generated in python, going from Jupyter notebooks to python packages. Here are some tool ideas:
  - A tools that calculate stats of reads mappability (I made a little tool called MApping Quality Control (MAPQC) and I have no idea what to do with it) or any tool that generates summaries and plots (Dani: ★★★★, Ben: ★★★☆)
  - A tool that uses machine learning (or even deep learning) to cluster multi-omics data (Dani: ★★☆☆, Ben: ★★☆☆)
  - A simplified version of one of the tools that you have developed related to GEMs (Dani: ★☆☆☆, Ben: ★★★★)
- **Genome-scale modeling**: this is out of my area of expertise, but I imagine it can be something related to E. coli? SS? (Dani: ★☆☆☆, Ben: ★★★★)

**Comment by dcsoto** [comment]
Food for thought: we could potentially include a Snakemake or Nextflow workflow within the "Analysis of NGS" section. It is important for working in a reproducible manner with large datasets. However, if the dataset is small, then other approaches are more time-efficient.

**Comment by BenjaSanchez** [comment]
Cool ideas! I have updated your comment with my own star rankings :) regarding genome-scale modeling:

* **Tool development:**
  - Simplified version of a tool developed related to GEMs: maybe [memote](https://github.com/opencobra/memote) (not developed by me but I think it's a gold standard in terms of tools) (Dani: ★☆☆☆, Ben: ★★★★)
* **Genome-scale modeling:** Would probably make this section smaller, as the community that works on this is significantly smaller than the other items. Would split it in 2 types:
  - Using a model for simulating simple conditions and predict some basic results (Ben: ★★★★)
  - Model generation and curation (both for small and larger developing teams), mentioning different version-control methdos out there (Ben: ★★★★)

> we could potentially include a Snakemake or Nextflow workflow within the "Analysis of NGS" section

Yes totally, I was intending for that to be a part of the "higher levels" of NGS analysis studies ;)
