### ISSUE TITLE
Change in citation syntax in latest rootstock version

### ISSUE THREAD

**Issue by dcsoto** [computer-aided-biotech/better-cb#19]
@BenjaSanchez there was a change in how to write citations. For example, websites should be written as: `@url:https://somewebsite.com`, and PubMed IDs changed from "pubmed" to "pmid".

Check the changes here: https://github.com/manubot/rootstock/blob/b422130eb46ea5d188779910772192730d79b172/USAGE.md

**Comment by BenjaSanchez** [comment]
@dcsoto I get a 404 error when I open that link, but the usual style `@https://somewebsite.com` and `@pubmed:26158728` works for me... I get the exact same output regardless of those options or `@url:https://somewebsite.com` and `@pmid:26158728`. Perhaps you are looking at an old version of the usage file? The current one proposes `@https://somewebsite.com` and `@pubmed:26158728` as current formats:

https://github.com/manubot/rootstock/blob/master/USAGE.md#citations

**Comment by dcsoto** [comment]
Sorry, I fixed the link! Indeed, it's an older version. But the reason why I dived into this was because the "newest" syntax was not working with the most recent version of rootstock in my Mac 🤷‍♀️  
But both syntax seem to pass the CI checks, so np!

**Comment by BenjaSanchez** [comment]
oh, did you eventually manage to make it work locally? If not, consider opening an issue at https://github.com/manubot/rootstock
