### ISSUE TITLE
fix: pdf not rendering properly

### ISSUE THREAD

**Issue by BenjaSanchez** [computer-aided-biotech/better-cb#22]
![image](https://user-images.githubusercontent.com/9384349/104627015-ce3b2d80-5696-11eb-8139-819c2583f67e.png)

@dcsoto could you confirm you see the same in your setup?

**Comment by dcsoto** [comment]
I fixed my MacBook! I rendered the file with no problems whatsoever. It's a Windows issue, apparently.

**Comment by BenjaSanchez** [comment]
@dcsoto great, the output that the CI creates also seems to be properly generated https://github.com/computer-aided-biotech/better-cb/blob/output/manuscript.pdf

will close the issue then, thanks for looking!
