### ISSUE TITLE
Draft figure 1

### ISSUE THREAD

**Issue by dcsoto** [computer-aided-biotech/better-cb#23]
I made some drafts for figure 1. Let me know which one is your favorite.

Option 1:
![Figure1-01](https://user-images.githubusercontent.com/7208981/104873716-01372880-5906-11eb-82d8-56ea2e2e1b1f.png)

Option 2:
![Figure1-02](https://user-images.githubusercontent.com/7208981/104873718-01372880-5906-11eb-8c9b-82a975afe5c5.png)

Option 3:
![Figure1-03](https://user-images.githubusercontent.com/7208981/104873719-01cfbf00-5906-11eb-8f74-05ac12338964.png)

Option 4:
![Figure1-04](https://user-images.githubusercontent.com/7208981/104873720-01cfbf00-5906-11eb-89c5-f2edff61fb83.png)

Option 5:
![Figure1-05](https://user-images.githubusercontent.com/7208981/104873721-01cfbf00-5906-11eb-950f-f833ee3a5910.png)

Also, let me know what you think about the text or if you have any other suggestions!

**Comment by BenjaSanchez** [comment]
They all look great! But options 3 and 4 are my favorite. Let's for now move ahead with any of them and next meeting we can discuss smaller details like color options, font, etc.

**Comment by dcsoto** [comment]
Excellent! I think GitHub reduced the image quality, because the images look better "in real life". I added a full resolution version in our shared GDrive.

Quick question: do we want to add the figure in the introduction section or somewhere else?

**Comment by BenjaSanchez** [comment]
Probably in the last paragraph of the introduction: _"[...] to access and engage over time with the developed research (Figure 1)."_
