### ISSUE TITLE
Draft Figure 2

### ISSUE THREAD

**Issue by dcsoto** [computer-aided-biotech/better-cb#26]
Here is a draft for Figure 2:

![Figure2](https://user-images.githubusercontent.com/7208981/108649405-19a0e280-7472-11eb-9367-80f0fd190d97.png)

Maybe the easiest way to convey the message would be a table, but we already have too many. Let's discuss this tomorrow!

**Comment by dcsoto** [comment]
Here is the new version of Figure 2! What do you think?

![Figure2](https://user-images.githubusercontent.com/7208981/109127501-5c2d1e00-7703-11eb-8a6b-6023079ded79.png)

**Comment by BenjaSanchez** [comment]
looks beautiful! Great choice of colors 👌 Maybe the arrows could have a design a bit more interesting, let's discuss in our next meeting.

**Comment by dcsoto** [comment]
Hi! Here is the new version of figure 2. @BenjaSanchez are the arrows interesting enough? 😂

![Figure2-new](https://user-images.githubusercontent.com/7208981/109440430-1dd77d80-79e7-11eb-98cb-10a27fd301af.png)

**Comment by BenjaSanchez** [comment]
@dcsoto absolutely, arrows look great!
