### ISSUE TITLE
Main topics to cover in Introduction

### ISSUE THREAD

**Issue by dcsoto** [computer-aided-biotech/better-cb#9]
Introduction's outline:

1. Importance of computation in biological research
2. Scope of sub-disciplines using computational biology (for the purpose of this review)
3. Types of computational biologist considered in this review  – data analysts, workflow designers, software developers, mathematical modelers, etc. (oftentimes we become a mixture of several of them)
4. Addressing the audience: computational biologists researchers
5. Importance of good practices in computational biology regardless of sub-disciplines (impact in reproducibility, collaboration, and overall, it's better science 😃 )
6. Where is the community so far in terms of best practices
7. Mentioning previous literature and some of their major takeaways and topics
8. Our premise: the computational biology best-practices continuum, best practices in individual research, collaboration, and community levels.
9. Introducing the manuscript structure and goals

^ Advice needed on structure and topics covered!

**Comment by BenjaSanchez** [comment]
I like the structure a lot! Would keep it like this for now until we have a proper draft, maybe then we revisit this ;)

**Comment by BenjaSanchez** [comment]
As this section is fully integrated to the manuscript in `master`, we can now close this issue.
